"""Contiene set di stopwords italiane"""
stopwords = ('farò', 'ad', 'della', 'queste', 'facevo', 'avevano', 'degli', 'stessi', 'avranno',
             'mia', 'sarai', 'stava', 'tuoi', 'lui', 'nell', 'fossimo', 'hanno', 'dalle', 'avuti',
             'tu', 'avessimo', 'sono', 'eri', 'facevate', 'stessimo', 'nel', 'avuto', 'questo', 'si',
             'avevamo', 'starò', 'mio', 'quanta', 'avessero', 'degl', 'alle', 'sullo', 'avessi', 'siete',
             'saranno', 'dov', 'starà', 'di', 'mie', 'ma', 'abbiamo', 'avremmo', 'avevi', 'suoi', 'stando',
             'stesse', 'starebbe', 'quelli', 'suo', 'farei', 'vostra', 'sua', 'feci', 'cui', 'siano',
             'faranno', 'ebbero', 'agli', 'ti', 'avrò', 'sei', 'tue', 'essendo', 'steste', 'anche', 'con',
             'dello', 'vostre', 'questi', 'che', 'nei', 'sia', 'contro', 'nostra', 'sareste', 'facevamo',
             'fossi', 'staresti', 'quanti', 'stetti', 'agl', 'facessi', 'abbiano', 'avremo', 'sulla', 'lo',
             'sui', 'uno', 'non', 'stiate', 'avete', 'farete', 'dei', 'stemmo', 'quella', 'starei', 'avuta',
             'fu', 'fareste', 'le', 'faccio', 'fece', 'facciamo', 'faremo', 'dagl', 'su', 'eravate', 'stavo',
             'avrà', 'voi', 'sarei', 'stavamo', 'tua', 'li', 'faremmo', 'all', 'quelle', 'facevano', 'ebbi',
             'avrete', 'o', 'stanno', 'sarebbero', 'dagli', 'un', 'sta', 'quale', 'facesti', 'facessimo',
             'avreste', 'è', 'farebbe', 'noi', 'avevo', 'farai', 'sugl', 'sarete', 'faceste', 'ai',
             'sugli', 'se', 'stavano', 'sul', 'c', 'allo', 'tutti', 'furono', 'tuo', 'saremmo', 'l',
             'stareste', 'vostro', 'stiamo', 'avrei', 'aveste', 'siamo', 'fummo', 'fosse', 'dove',
             'fanno', 'io', 'una', 'nelle', 'alla', 'negli', 'nostro', 'dell', 'il', 'avrebbero',
             'facessero', 'questa', 'avresti', 'stiano', 'starai', 'stette', 'era', 'starete',
             'quello', 'avemmo', 'facciano', 'ed', 'hai', 'avesti', 'siate', 'foste', 'facendo',
             'come', 'stettero', 'nella', 'eravamo', 'starebbero', 'erano', 'coi', 'ha', 'dal',
             'nostri', 'facesse', 'staremmo', 'dalla', 'tutto', 'e', 'la', 'ne', 'avesse', 'più',
             'abbia', 'stia', 'fossero', 'loro', 'fosti', 'dai', 'abbiate', 'fai', 'staremo', 'gli',
             'dall', 'nello', 'faceva', 'avute', 'col', 'sarebbe', 'vostri', 'farebbero', 'fui',
             'ci', 'da', 'miei', 'sto', 'ero', 'sulle', 'ebbe', 'mi', 'avrai', 'lei', 'tra', 'aveva',
             'facevi', 'fecero', 'perché', 'quante', 'sue', 'sarò', 'saresti', 'al', 'sarà', 'in',
             'per', 'facciate', 'avevate', 'facemmo', 'stavate', 'dallo', 'saremo', 'stai', 'quanto',
             'chi', 'i', 'avrebbe', 'sull', 'stavi', 'farà', 'stessero', 'negl', 'del', 'nostre', 'ho',
             'faresti', 'vi', 'delle', 'staranno', 'stesti', 'faccia', 'avendo', 'a')
