# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attivita', '0002_attivita_proprietario'),
    ]

    operations = [
        migrations.CreateModel(
            name='RicercaComplessa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo_citta', models.CharField(blank=True, max_length=25, verbose_name='citta')),
                ('testo_nome', models.CharField(blank=True, max_length=25, verbose_name='nome')),
                ('tipologie', models.ManyToManyField(blank=True, to='attivita.Tipologia')),
            ],
        ),
        migrations.CreateModel(
            name='RicercaSemplice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.CharField(max_length=25)),
            ],
        ),
    ]
