# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 10:40
from __future__ import unicode_literals

import attivita.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attivita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('indirizzo', models.CharField(max_length=50, verbose_name='Indirizzo')),
                ('citta', models.CharField(max_length=30, verbose_name='Città')),
                ('reputazione', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Reputazione')),
                ('descrizione', models.TextField(blank=True, max_length=500, verbose_name='Descrizione')),
                ('latitudine', models.FloatField(blank=True, null=True, verbose_name='Latitudine')),
                ('longitudine', models.FloatField(blank=True, null=True, verbose_name='Longitudine')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=20)),
                ('immagine', models.ImageField(upload_to=attivita.models.get_upload_path)),
                ('tagcloud', models.BooleanField(default=False)),
                ('attivita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attivita.Attivita')),
            ],
        ),
        migrations.CreateModel(
            name='Tipologia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Useless Tipology', max_length=25, unique=True, verbose_name='nome')),
            ],
        ),
        migrations.AddField(
            model_name='attivita',
            name='tipologie',
            field=models.ManyToManyField(blank=True, to='attivita.Tipologia'),
        ),
    ]
