# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attivita', '0002_attivita_proprietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='filename',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
