# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attivita', '0002_attivita_proprietario'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data di pubblicazione')),
                ('voto', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='Voto')),
                ('testo', models.TextField(verbose_name='Testo Recensione')),
                ('utilita', models.IntegerField(default=0)),
                ('attivita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attivita.Attivita')),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
                ('votanti', models.ManyToManyField(blank=True, related_name='votanti', to='users.UserProfile')),
            ],
            options={
                'permissions': (('can_vote_review', 'Can Vote Review'),),
            },
        ),
    ]
