# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recensioni', '0002_auto_20180331_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recensione',
            name='attivita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attivita.Attivita'),
        ),
    ]
