# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recensioni', '0003_auto_20180331_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recensione',
            name='testo',
            field=models.TextField(max_length=1000, verbose_name='Testo Recensione'),
        ),
    ]
